---
- name: Deploying application
  hosts: all
  vars_files:
    - "vars/default.yml"
    - "vars/deploy.yml"
  roles:
    - common
    - nodejs
    - predeploy
    - { role: weareinteractive.pm2, sudo: yes }
