---
- name: Deploying application
  hosts: all
  vars_files:
    - "vars/default.yml"
    - "vars/deploy.yml"
  roles:
    - common
    - nodejs
    - { role: weareinteractive.pm2, sudo: yes }
    - scripts
    - ssmtp                                                                                                    
  tasks:
    - name:
      cron:
        name: "Set email cron job"
        minute: "0"
        hour: "0"
        job: "logparser | mail -s 'Web server daily log' {{ ssmtp_receiver }}"
