---
- name: Deploying application
  hosts: all
  vars_files:
    - "vars/default.yml"
    - "vars/deploy.yml"
  roles:
    - common
    - nodejs
    - { role: weareinteractive.pm2, sudo: yes }
  tasks:
    - name: Copying load_tests script
      copy:
        src: "{{ inventory_dir }}/scripts/load_tests.sh"
        dest: /usr/local/bin/load_tests
        mode: 0755
      become: true
      become_user: root
