- name: weareinteractive.pm2
  src: https://github.com/raphapr/ansible-pm2
  version: origin/master

- name: jdauphant.nginx
  src: https://github.com/raphapr/ansible-role-nginx
  version: origin/master

- src: jdauphant.ssl-certs
