  - name: update apt packages
    apt: 
      update_cache: yes 
      cache_valid_time: 3600

  - name: Add the Nodesource apt key
    apt_key: 
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key 
      state: present
    become: true
    become_user: root
   
  - name: Add nodesource repository
    apt_repository: 
      repo: deb https://deb.nodesource.com/node_{{ nodejs_version }} xenial main
      state: present
    become: true
    become_user: root
   
  - name: Install nodejs and some dependencies
    apt: 
      name: "{{ item }}"
      update_cache: yes 
      state: present
    with_items:
        - nodejs
        - build-essential
    become: true
    become_user: root

  - name: Install pm2 nodejs package globally.
    npm:
      name: pm2
      global: yes
      state: latest
    become: true
    become_user: root
