---
#Configuration
repo_url: https://github.com/raphapr/lnc-challenge.git
repo_version: master
app_name: lncserver
nodejs_version: 6.x

# pm2
pm2_user: root
pm2_service_name: pm2-root
pm2_service_enabled: yes
pm2_service_state: started

# for let's encrypt
certbot_auto_renew_user: "{{ ansible_user_id }}"
certbot_auto_renew_minute: 20
certbot_auto_renew_hour: 5
