#Configuration
repo_version: master
app_name: lncserver
nodejs_version: 6.x
timezone: America/Maceio

# pm2
pm2_user: root
pm2_service_name: pm2-root
pm2_service_enabled: yes
pm2_service_state: started

# ssmtp
ssmtp_root: lnc.chall3ng3@gmail.com
ssmtp_mailhub: smtp.gmail.com:587
ssmtp_hostname: localhost
ssmtp_rewrite_domain: gmail.com
ssmtp_auth_user: lnc.chall3ng3@gmail.com
ssmtp_auth_pass: dexqiyfdavjeimgc
ssmtp_use_starttls: "YES"
ssmtp_use_tls: "YES"
ssmtp_from_line_override: "YES"

# email receiver
ssmtp_receiver: lnc.chall3ng3@gmail.com
