---
- name: Deploying application
  hosts: all
  sudo: yes
  vars_files:
    - ["vars/default.yml"]
  roles:
    - common
    - weareinteractive.pm2
  pre_tasks:

    - name: Add the Nodesource apt key
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key 
        state: present
      become: true
      become_user: root
     
    - name: Add nodesource repository
      apt_repository: 
        repo: deb https://deb.nodesource.com/node_{{ nodejs_version }} xenial main
        state: present
      become: true
      become_user: root
     
    - name: Install nodejs and some dependencies
      apt: 
        name: "{{ item }}"
        update_cache: yes 
        state: present
      with_items:
          - nodejs
          - build-essential
      become: true
      become_user: root

    - name: creating deploy directory
      file: 
        path: "{{ deploy_app_dir }}"
        state: directory
        mode: 0755

    - name: Pull sources from the repository.
      git: 
        repo: "{{ repo_url }}"
        dest: "{{ deploy_app_dir }}"
        version: "{{ repo_version }}"

    - name: Install packages based on package.json
      npm:
        path: "{{ deploy_app_dir }}/src"
        state: present
      become: true
      become_user: root
