---
- name: Deploying application
  hosts: all
  vars_files:
    - ["vars/default.yml"]
  roles:
    - common
    - nodejs
  tasks:
    - name: Install global npm packages
      npm: name={{ item }} global=yes
      become_user: root
      with_items:
        - pm2

    - name: Make app dir
      become_user: root
      shell: mkdir -p {{ deploy_app_dir }}

    - name: Pull sources from the repository.
      sudo: no
      git: repo={{ repo_url }}
           dest={{ deploy_app_dir }}
           version={{ repo_version }}

    - name: install npm packages for root
      sudo: no
    shell: chdir={{ deploy_app_dir }}/src npm install
