---
  - name: update apt packages
    apt: update_cache=yes cache_valid_time=3600
    become: yes
    become_user: root

  - name: install basic apt packages
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
    become: yes
    become_user: root
