---
#Configuration
repo_url: https://github.com/raphapr/lnc-challenge.git
repo_version: master
app_name: lncserver
nodejs_version: 6.x
deploy_dir: "/var/apps/{{ app_name }}"
deploy_app_dir: "/var/apps/{{ app_name }}/{{ app_name }}-current"
deploy_app_src: "/var/apps/{{ app_name }}/{{ app_name }}-current/src"
rollback_app_dir: "/var/apps/{{ app_name }}/{{ app_name }}-before"
rollback_app_src: "/var/apps/{{ app_name }}/{{ app_name }}-before/src"

# pm2
pm2_user: root
pm2_service_name: pm2-root
pm2_apps_default_env:
  NODE_ENV: production
pm2_cmds:
- run: delete
  args: console_error
  ignore_errors: yes
pm2_apps:
- run: apps.json
  path: "{{ deploy_app_dir }}/src"
  cmd: startOrGracefulReload
#- run: console_error.js
  #args: --name console_error
  #path: "{{ deploy_app_dir }}/src/console_log"
  #cmd: start
  env:
    NODE_ENV: development
