---
#Configuration
repo_url: https://github.com/raphapr/lnc-challenge.git
repo_version: master
app_name: lncserver
nodejs_version: 6.x
deploy_dir: "/var/apps/{{ app_name }}"
deploy_app_dir: "/var/apps/{{ app_name }}/{{ app_name }}-current"
rollback_app_dir: "/var/apps/{{ app_name }}/{{ app_name }}-before"

# pm2
pm2_user: root
pm2_service_name: pm2-root
pm2_service_enabled: yes
pm2_service_state: started
pm2_apps:
- run: apps.json
  path: "{{ deploy_app_dir }}/src"
  cmd: startOrGracefulReload
  env:
    NODE_ENV: development

# for let's encrypt
certbot_auto_renew_user: "{{ ansible_user_id }}"
certbot_auto_renew_minute: 20
certbot_auto_renew_hour: 5
