    - name: creating deploy directory
      file: 
        path: "{{ deploy_app_dir }}"
        state: directory
        mode: 0755

    - name: Pull sources from the repository.
      git: 
        repo: "{{ repo_url }}"
        dest: "{{ deploy_app_dir }}"
        version: "{{ repo_version }}"

    - name: Install packages based on package.json
      npm:
        path: "{{ deploy_app_dir }}/src"
        state: present
      become: true
      become_user: root
